# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'windows-2019'

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'spn'
      subscriptionId: '3c04e122-5492-401c-9c2f-947eccf22a11'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'arvinmyrg34'
      location: 'East US'
      templateLocation: 'Linked artifact'
      csmFile: 'resource-group/azuredeploy.json'
      csmParametersFile: 'resource-group/metadata.json'
      deploymentMode: 'Validation'
